### ISSUE TITLE
Xcode 16 beta error when uploading build to testflight

### ISSUE THREAD

**Issue by EugeniuszX** [shakebugs/shake-react-native#6]
![2024-06-26 10 34 50](https://github.com/shakebugs/shake-react-native/assets/63192915/8bd8841c-b25d-48ef-98cb-6dd40b5db120)

**Comment by surafelbm** [comment]
@EugeniuszX , were you able to fix this?

**Comment by lundb1tr** [comment]
Also seeing this.

**Comment by surafelbm** [comment]
@lundb1tr , adding a script inside podfile post-install to remove the bitcode seems to work here is the code:

```
# Bitcode stripping logic
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  # Add the paths for Shake framework here
  framework_paths = [
    "Pods/Shake/Sources/Shake.xcframework/ios-arm64/Shake.framework/Shake",
    "Pods/Shake/Sources/Shake.xcframework/ios-arm64_x86_64-simulator/Shake.framework/Shake"
  ]

  # Execute bitcode stripping for the specified paths
  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end
```

**Comment by lundb1tr** [comment]
> @lundb1tr , adding a script inside podfile post-install to remove the bitcode seems to work here is the code:
> 
> ```
> # Bitcode stripping logic
>   bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
> 
>   def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
>     framework_path = File.join(Dir.pwd, framework_relative_path)
>     command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
>     puts "Stripping bitcode: #{command}"
>     system(command)
>   end
> 
>   # Add the paths for Shake framework here
>   framework_paths = [
>     "Pods/Shake/Sources/Shake.xcframework/ios-arm64/Shake.framework/Shake",
>     "Pods/Shake/Sources/Shake.xcframework/ios-arm64_x86_64-simulator/Shake.framework/Shake"
>   ]
> 
>   # Execute bitcode stripping for the specified paths
>   framework_paths.each do |framework_relative_path|
>     strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
>   end
> ```

Thank you, I will look into implementing this as part of our release flow for the version of the app that has Shake.

**Comment by mstanic-shake** [comment]
https://github.com/shakebugs/shake-ios/issues/38

Please check this issue
