### ISSUE TITLE
Not working on android with Expo SDK 52

### ISSUE THREAD

**Issue by visiot-dev** [shakebugs/shake-react-native#9]
After upgrading the app from Expo 51.0.37 to Expo 52.0.0, I was unable to run the app on Android, then went back again to version 51.0.37 and tried running it, worked without any errors

### `Error: Exception in HostObject::get for prop ‘RNShake’: com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotations from native module: RNShake. Details: Module exports two methods to JavaScript with the same name: “show [Component Stack]`

**Comment by mstanic-shake** [comment]
https://github.com/shakebugs/shake-react-native/issues/8

Duplicate issue
